name: Daily AQI Pipeline

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6 AM
  workflow_dispatch:       # Also allows manual run

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AQI Pipeline
        run: python src/fetch_aqi.py